CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	user_id VARCHAR(255) UNIQUE NOT NULL,
	username VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	gender VARCHAR(50) NOT NULL,
	sexual_orientation VARCHAR(50) NOT NULL,
	bio TEXT,
	age INTEGER NOT NULL,
	tags VARCHAR(255)[],
	frame_rate INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS auth (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
