CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	user_id VARCHAR(255) UNIQUE NOT NULL,
	username VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	gender VARCHAR(50) NOT NULL,
	sexual_orientation VARCHAR(50) NOT NULL DEFAULT 'bisexual',
	bio TEXT DEFAULT '',
	age INTEGER NOT NULL,
	frame_rate INTEGER NOT NULL DEFAULT 0,
	is_online BOOLEAN NOT NULL DEFAULT FALSE,
	last_online TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
