CREATE TABLE IF NOT EXISTS user_tags (
	user_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,

	PRIMARY KEY (user_id, tag_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
