CREATE TABLE IF NOT EXISTS user_images (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	image_url TEXT NOT NULL,
	is_profile BOOLEAN NOT NULL DEFAULT FALSE,
	position INTEGER NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);