services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./server/vhosts.conf:/usr/local/apache2/conf/extra/vhosts.conf
      - ./server/certificates:/usr/local/apache2/conf/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - default

  #Note: expose only for tests, not for production
  frontend:
    build: ./frontend
    environment:
      - NODE_EXTRA_CA_CERTS=/app/ssl/server.cert
    volumes:
      - ./server/certificates:/app/ssl:ro
    expose:
      - "3000"
    networks:
      - default

  backend:
    build: ./backend
    volumes:
      - ./server/certificates:/certificates
    expose:
      - "5000"
    networks:
      - default
      - db_network
  
  database:
    image: postgres:latest
    networks:
      - db_network
    volumes:
      - ./database/data:/var/lib/postgresql #persist data
      - ./database/init:/docker-entrypoint-initdb.d
    env_file:
      - ./database/.env

networks:
  db_network:
    driver: bridge
  default:
    driver: bridge
